# Generated by Django 2.0.2 on 2018-03-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Common',
            new_name='Comment',
        ),
    ]
